# This is the default config file for icp2edd

paths:
    # erddap: path of the main ERDDAP repository [tomcat]
    erddap: '/home/jpa029/Code/apache-tomcat-8.5.57'
    # dataset: path where store file from each dataset
    dataset:
        # path where store csv file from ICOS CP for each dataset
        csv: '/home/jpa029/Data/ICOS2ERDDAP'
        # path where store xml file from ICOS CP for each dataset
        xml: '/home/jpa029/Data/ICOS2ERDDAP/dataset'
    # log: path where store output log file
    log: '/home/jpa029/Data/ICOS2ERDDAP/log'

subm:
    # from: dataset submitted from [default: end date of last update]
    # from: '2020-01-01T00:00:00.000Z'
    # until: dataset submitted until [default: today]
    # until: '05-08-2020'
    # product: data 'type' selected
    product: 'icosOtcL2Product'
    # version: get only last version [default False]
    version: True
    # list of authorised product
    authorised_product: ['icosOtcL1Product_v2', 'icosOtcL2Product']

log:
    # filename: logger filename
    # filename:
    # below, apply only on standard output log
    # TODO find a way to make it work, overwrite by argument
    # verbose: activate verbose mode [True|False]
    verbose: False
    # level: log level [DEBUG, INFO, WARN, ERROR, CRITICAL]
    level: 'INFO'